blank_issues_enabled: false
contact_links:
  - name: Something else
    url: https://github.com/orgs/FossifyOrg/discussions/new/choose
    about: Please use this option only if your issue is not a bug report or a feature request. 
