name: Feature request
description: Suggest an idea for this project
labels: [ "feature request", "needs triage" ]
body:
  - type: markdown
    attributes:
      value: |
        ## Hi there 👋
        Thanks for helping us improve Fossify by suggesting a feature!
        Please fill in as much information as possible about your feature request to avoid unnecessary and time-consuming back-and-forth communication.

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/General-Discussion/issues) or [closed](https://github.com/FossifyOrg/General-Discussion/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information."
          required: true
        - label: "I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/General-Discussion/discussions) or [closed](https://github.com/FossifyOrg/General-Discussion/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information."
          required: true
        - label: "I have read the FAQs inside the app (Menu -> About -> FAQs), in the [README](https://github.com/FossifyOrg/General-Discussion/blob/master/README.md) and my problem isn't listed."
          required: true
        - label: "**I have taken the time to fill in all the required details. I understand that the request may get dismissed otherwise.**"
          required: true
        - label: "This issue contains only one feature request."
          required: true
        - label: "I optionally [donated](https://fossify.org/donate) to support the Fossify mission."
          required: false

  - type: dropdown
    id: affected-apps
    attributes:
      label: Which apps should have this feature?
      multiple: true
      options:
        - All Fossify Apps
        - App Launcher
        - Calculator
        - Calendar
        - Camera
        - Clock
        - Contacts
        - Draw
        - File Manager
        - Flashlight
        - Gallery
        - Keyboard
        - Launcher
        - Messages
        - Music Player
        - Notes
        - PDF Viewer
        - Phone
        - Thank You
        - Voice Recorder

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: |
        Explain how you want the app's look or behavior to change to suit your needs.
        
        ⚠️ Please **DO NOT** add links to SimpleMobileTools issues as they can be deleted at any time. Instead, copy-paste any useful information manually.
    validations:
      required: true

  - type: textarea
    id: why-is-the-feature-requested
    attributes:
      label: Why do you want this feature?
      description: |
        Describe any problem or limitation you come across while using the app which would be solved by this feature.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other information you'd like to include, for instance sketches, mockups, pictures of rabbits, etc.
